apisix:
  enable_ipv6: false
  ssl:
    enable: false
  node_listen: 9080
  enable_admin: true
  allow_admin:
    - 0.0.0.0/0
  

deployment:
  admin:
    admin_key:
      - name: "admin"
        key: QORRRZHORxKqDxXGpuUTPCxYOVrQXFVX
        role: admin
    admin_listen:
      ip: "0.0.0.0"
      port: 9180
    enable_admin_cors: true
    allow_admin:
      - 0.0.0.0/0
  
  etcd:
    host:
      - "http://etcd:2379"
    prefix: "/apisix"
    timeout: 30